const recipes = [

    {   id:1,
        name: "Spaghetti Carbonara", 
        chef: "Chef Mario",
        totalRatings: 500,
        avgRating: 4.8,
        uploadedOn: "2024-01-15", 
        mealType: "Dinner", 
        dishType: "Pasta", 
        testKitchenApproved: true,
        contestWinner: false,
        featured: false, 
        description: "A classic Italian pasta dish with a creamy egg-based sauce and crispy pancetta.",
        imgUrl: "https://i.pinimg.com/564x/a9/0e/e4/a90ee4bca901e935a7a406a7d90ca6c2.jpg"
        },
        

    {
        id:2,    
        name: "Pizza Margherita",
        chef: "Chef Giovanni", 
        totalRatings: 400, 
        avgRating: 4.6, 
        uploadedOn: "2024-02-10",
        mealType: "Dinner", 
        dishType: "Pizza",
        testKitchenApproved: false, 
        contestWinner: true,
        featured: true, 
        description: "A classic Italian pizza with a classic tomato sauce, mozzarella, and basil.", 
        imgUrl: "https://cdn.pixabay.com/photo/2023/05/28/14/13/ai-generated-8023787_960_720.jpg"
        },
    {
        id: 3,
        name: "Spicy Chicken Curry",
        chef: "Gordon Ramsay",
        totalRatings: 320,
        avgRating: 4.8,
        uploadedOn: "2024-02-20",
        mealType: "Dinner",
        dishType: "Curry",
        testKitchenApproved: true,
       contestWinner: false,
       featured: true,
       description: "A rich and flavorful spicy chicken curry cooked with aromatic spices.",
       imgUrl: "https://cdn.pixabay.com/photo/2023/06/02/19/10/ai-generated-8036252_1280.jpg"
  },
  {
    id: 4,
    name: "Seafood Paella",
    chef: "José Andrés",
    totalRatings: 350,
    avgRating: 4.6,
    uploadedOn: "2024-02-05",
    mealType: "Dinner",
    dishType: "Seafood",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "A classic Spanish paella with fresh seafood and saffron-infused rice.",
    imgUrl: "https://cdn.pixabay.com/photo/2025/01/18/09/11/ai-generated-9341727_960_720.png"
  }, 
  {
    id: 5,
    name: "Blueberry Smoothie",
    chef: "Martha Stewart",
    totalRatings: 180,
    avgRating: 4.5,
    uploadedOn: "2024-03-01",
    mealType: "Breakfast",
    dishType: "Smoothie",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A refreshing blueberry smoothie packed with antioxidants and flavor.",
    imgUrl: "https://cdn.pixabay.com/photo/2024/06/04/12/22/drink-8808532_960_720.png"
  },
  {
    id: 6,
    name: "Classic Tomato Soup",
    chef: "Ina Garten",
    totalRatings: 220,
    avgRating: 4.7,
    uploadedOn: "2024-01-22",
    mealType: "Lunch",
    dishType: "Soup",
    testKitchenApproved: true,
    contestWinner: false,
    featured: true,
    description: "A creamy and delicious tomato soup perfect for a cozy meal.",
    imgUrl: "https://cdn.pixabay.com/photo/2023/10/18/08/38/tomato-8323289_960_720.jpg"
  },
  {
    id: 7,
    name: "Butter Chicken",
    chef: "Sanjeev Kapoor",
    totalRatings: 400,
    avgRating: 4.9,
    uploadedOn: "2024-02-28",
    mealType: "Dinner",
    dishType: "Curry",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "A creamy and rich Indian butter chicken recipe with authentic spices.",
    imgUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  },
  {
    id: 8,
    name: "Chocolate Lava Cake",
    chef: "Dominique Ansel",
    totalRatings: 500,
    avgRating: 5.0,
    uploadedOn: "2024-01-05",
    mealType: "Dessert",
    dishType: "Cake",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "A decadent chocolate lava cake with a gooey molten center.",
    imgUrl: "https://cdn.pixabay.com/photo/2024/06/28/06/14/cakes-8858646_960_720.jpg"
  },
  {
    id: 9,
    name: "Caesar Salad",
    chef: "Wolfgang Puck",
    totalRatings: 150,
    avgRating: 4.3,
    uploadedOn: "2024-02-10",
    mealType: "Lunch",
    dishType: "Salad",
    testKitchenApproved: false,
    contestWinner: false,
    featured: false,
    description: "A fresh Caesar salad with crunchy croutons and homemade dressing.",
    imgUrl: "https://images.unsplash.com/photo-1607532941433-304659e8198a?q=80&w=1378&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  },
  {
    id: 10,
    name: "Mango Lassi",
    chef: "Ranveer Brar",
    totalRatings: 120,
    avgRating: 4.6,
    uploadedOn: "2024-03-12",
    mealType: "Breakfast",
    dishType: "Smoothie",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A refreshing and creamy mango lassi made with fresh mango and yogurt.",
    imgUrl: "https://cdn.pixabay.com/photo/2024/04/23/07/10/ai-generated-8714181_1280.jpg"
  },
  {
    id: 11,
    name: "Vegetable Stir Fry",
    chef: "David Chang",
    totalRatings: 210,
    avgRating: 4.4,
    uploadedOn: "2024-02-15",
    mealType: "Dinner",
    dishType: "Vegetarian",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A colorful stir fry with fresh vegetables and a savory sauce.",
    imgUrl: "https://plus.unsplash.com/premium_photo-1664472637341-3ec829d1f4df?q=80&w=1450&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  },
  {
    id: 12,
    name: "Pancakes with Maple Syrup",
    chef: "Bobby Flay",
    totalRatings: 330,
    avgRating: 4.8,
    uploadedOn: "2024-01-10",
    mealType: "Breakfast",
    dishType: "Pancakes",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "Fluffy pancakes served with pure maple syrup and fresh berries.",
    imgUrl: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  } ,
  {
    id: 13,
    name: "Mexican Tacos",
    chef: "Rick Bayless",
    totalRatings: 270,
    avgRating: 4.7,
    uploadedOn: "2024-03-10",
    mealType: "Dinner",
    dishType: "Mexican",
    testKitchenApproved: false,
    contestWinner: false,
    featured: false,
    description: "Authentic Mexican tacos with a choice of beef, chicken, or vegetarian filling.",
    imgUrl: "https://plus.unsplash.com/premium_photo-1679231521293-e13146411fb2?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  },
  {
    id: 14,
    name: "Penne Alfredo",
    chef: "Gordon Ramsay",
    totalRatings: 380,
    avgRating: 4.7,
    uploadedOn: "2024-02-20",
    mealType: "Lunch",
    dishType: "Pasta",
    testKitchenApproved: true,
    contestWinner: false,
    featured: true,
    description: "Classic creamy Alfredo pasta with Parmesan cheese and herbs.",
    imgUrl: "https://cdn.pixabay.com/photo/2024/09/30/12/36/salad-9085796_960_720.jpg"
  },
  {
    id: 15,
    name: "Strawberry Pancakes",
    chef: "Nigella Lawson",
    totalRatings: 275,
    avgRating: 4.6,
    uploadedOn: "2024-03-05",
    mealType: "Breakfast",
    dishType: "Pancakes",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "Fluffy pancakes topped with fresh strawberries and maple syrup.",
    imgUrl: "https://images.unsplash.com/photo-1673646961450-8432d46e3a40?q=80&w=1545&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  },
  {
    id: 16,
    name: "Tandoori Paneer Tikka",
    chef: "Vikas Khanna",
    totalRatings: 500,
    avgRating: 4.8,
    uploadedOn: "2024-02-01",
    mealType: "Dinner",
    dishType: "Appetizer",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "Grilled paneer cubes marinated in flavorful Indian spices.",
    imgUrl: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=1617&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  },
  {
    id: 17,
    name: "Avocado Toast",
    chef: "Jamie Oliver",
    totalRatings: 320,
    avgRating: 4.5,
    uploadedOn: "2024-01-25",
    mealType: "Breakfast",
    dishType: "Toast",
    testKitchenApproved: false,
    contestWinner: false,
    featured: false,
    description: "Whole-grain toast topped with creamy avocado, chili flakes, and lemon juice.",
    imgUrl: "https://plus.unsplash.com/premium_photo-1676106623114-e2edc4f04fe0?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  },
  {
    id: 18,
    name: "Chocolate Brownie",
    chef: "Rachel Allen",
    totalRatings: 290,
    avgRating: 4.9,
    uploadedOn: "2024-03-08",
    mealType: "Dessert",
    dishType: "Brownie",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "Rich, fudgy chocolate brownies with a hint of sea salt.",
    imgUrl: "https://cdn.pixabay.com/photo/2023/01/25/08/25/cookies-7742773_1280.jpg"
  },
  {
    id: 19,
    name: "Greek Salad",
    chef: "Yotam Ottolenghi",
    totalRatings: 230,
    avgRating: 4.7,
    uploadedOn: "2024-02-18",
    mealType: "Lunch",
    dishType: "Salad",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A refreshing Greek salad with feta cheese, olives, and a tangy dressing.",
    imgUrl: "https://images.unsplash.com/photo-1607532941433-304659e8198a?q=80&w=1378&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  },
  { id:20,
    name: "Biscotti",
    chef: "Chef Francesco",
    totalRatings: 5,
    avgRating: 3.6,
    uploadedOn: "2025-02-10",
    mealType: "Snack",
    dishType: "Cookies",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A classic Italian cookie that's twice-baked to produce a crunchy exterior and a soft interior.",
    imgUrl: "https://cdn.pixabay.com/photo/2024/04/01/06/57/cookies-8668140_960_720.jpg"
    },
       
    ]





export default  recipes